server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/florestal_prod
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
